from django.db import models

class Publisher(models.Model):
    name = models.CharField(max_length = 30)
    city = models.CharField(max_length = 30)
    date = models.IntegerField()

# Create your models here.
class DataSet(models.Model):
    metaData = models.CharField(max_length = 500)
    name = models.CharField(max_length = 50)
"""class Point(models.Model):
    dataSet = models.ForeignKey(DataSet) 
    QX = models.FloatField()
    QY = models.FloatField()
    QZ = models.FloatField()
    E = models.FloatField()
    A1 = models.FloatField()
    A2 = models.FloatField()
    A3 = models.FloatField()
    A4 = models.FloatField()
    A5 = models.FloatField()
    A6 = models.FloatField()
    Time = models.FloatField()
    Temp = models.FloatField()
    Detector = models.IntegerField()
    Monitor = models.FloatField()
    DFMRot = models.FloatField()
    DFM = models.FloatField()
    AnalyzerBlade01 = models.FloatField()
    AnalyzerBlade02 = models.FloatField()
    AnalyzerBlade03 = models.FloatField()
    AnalyzerBlade04 = models.FloatField()
    AnalyzerBlade05 = models.FloatField()
    AnalyzerBlade06 = models.FloatField()
    AnalyzerBlade07 = models.FloatField()
    AnalyzerBlade08 = models.FloatField()
    AnalyzerBlade09 = models.FloatField()
    AnalyzerBlade10 = models.FloatField()
    AnalyzerBlade11 = models.FloatField()
    AnalyzerBlade12 = models.FloatField()
    AnalyzerBlade13 = models.FloatField()
    AnalyzerRotation = models.FloatField()
    ApertHori = models.FloatField()
    ApertVert = models.FloatField()
    BkSltHght = models.FloatField()
    BkSltWdth = models.FloatField()
    DDC0 = models.FloatField()
    DDC1 = models.FloatField()
    DDC2 = models.FloatField()
    DiffDet = models.FloatField()
    EFcancel = models.FloatField()
    EFflip = models.FloatField()
    EFguide = models.FloatField()
    EIcancel = models.FloatField()
    EIflip = models.CharField(max_length = 10)
    EIguide = models.FloatField()
    FLIP = models.FloatField()
    FilRot = models.CharField(max_length = 10)
    FilTilt = models.FloatField()
    FilTran = models.FloatField()
    FocusCu = models.FloatField()
    FocusPG = models.FloatField()
    H = models.FloatField()
    HKL = models.FloatField()
    Hsample = models.FloatField()
    K = models.FloatField()
    L = models.FloatField()
    Monitor2 = models.FloatField()
    MonoBlade01 = models.FloatField()
    MonoBlade02 = models.FloatField()
    MonoBlade03 = models.FloatField()
    MonoBlade04 = models.FloatField()
    MonoBlade05 = models.FloatField()
    MonoBlade06 = models.FloatField()
    MonoBlade07 = models.FloatField()
    MonoBlade08 = models.FloatField()
    MonoBlade09 = models.FloatField()
    MonoBlade10 = models.FloatField()
    MonoElev = models.FloatField()
    MonoTrans = models.FloatField()
    PSDet = models.FloatField()
    PostAnaColl = models.FloatField()
    PreMonoColl = models.FloatField()
    RC = models.FloatField()
    SC = models.FloatField()
    SDC0 = models.FloatField()
    SDC1 = models.FloatField()
    SDC2 = models.FloatField()
    SingleDet = models.FloatField()
    SmplElev = models.FloatField()
    SmplGFRot = models.FloatField()
    SmplLTilt = models.FloatField()
    SmplLTrn = models.FloatField()
    SmplUTilt = models.FloatField()
    SmplUTrn = models.FloatField()
    TDC00 = models.FloatField()
    TDC01 = models.FloatField()
    TDC02 = models.FloatField()
    TDC03 = models.FloatField()
    TDC04 = models.FloatField()
    TDC05 = models.FloatField()
    TDC06 = models.FloatField()
    TDC07 = models.FloatField()
    TDC08 = models.FloatField()
    TDC09 = models.FloatField()
    TDC10 = models.FloatField()
    Vsample = models.FloatField()
    TemperatureControlReading = models.FloatField()
    TemperatureSetpoint = models.FloatField()
    TemperatureHeaterPower = models.FloatField()
    TemperatureSensor1 = models.FloatField()
    TemperatureSensor2 = models.FloatField()
    TemperatureSensor3 = models.FloatField()"""
#END
