from django.db import models

# Create your models here.
class DataFile(models.Model):
    metaData = models.CharField(max_length = 500)
    name = models.CharField(max_length = 50)
#END

class Point(models.Model):
    fileid = models.ForeignKey(DataFile)
    a1 = models.CharField(max_length = 50)
    a2 = models.CharField(max_length = 50)
    a3 = models.CharField(max_length = 50)
    a4 = models.CharField(max_length = 50)
    a5 = models.CharField(max_length = 50)
    a6 = models.CharField(max_length = 50)
    sample_elevator = models.CharField(max_length = 50)
    sample_upper_tilt = models.CharField(max_length = 50)
    sample_upper_translation = models.CharField(max_length = 50)
    sample_lower_tilt = models.CharField(max_length = 50)
    sample_upper_translation = models.CharField(max_length = 50)
    dfm_rotation = models.CharField(max_length = 50)
    analyzer_rotation = models.CharField(max_length = 50)
    h = models.CharField(max_length = 50)
    k = models.CharField(max_length = 50)
    l = models.CharField(max_length = 50)
    e = models.CharField(max_length = 50)
    qx = models.CharField(max_length = 50)
    qy = models.CharField(max_length = 50)
    qz = models.CharField(max_length = 50)
    hkl = models.CharField(max_length = 50)
    name = models.CharField(max_length = 50)
    vertical_focus = models.CharField(max_length = 50)
    horizontal_focus = models.CharField(max_length = 50)
    blades = models.CharField(max_length = 50)
    mosaic = models.CharField(max_length = 50)
    dspacing = models.CharField(max_length = 50)
    focus_cu = models.CharField(max_length = 50)
    focus_pg = models.CharField(max_length = 50)
    translation = models.CharField(max_length = 50)
    elevation = models.CharField(max_length = 50)
